#!/bin/bash

echo "this is about sum of two number's "

echo "this program is read value from user"

echo "pls enter the value of : a"

read a

echo "pls enter the value of : b"

read b

sum=$((a+b))

echo "the sum of a and b is : $sum "

